name: ci

on: [ push, pull_request ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: leafo/gh-actions-lua@v8
      - uses: leafo/gh-actions-luarocks@v4
      - run: luarocks install luacheck
      - run: luacheck .
